# Generated by Django 5.0.3 on 2024-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='album_obj',
            new_name='album_object',
        ),
    ]
